version: "3"
services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: docker/postgres.Dockerfile
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=ngk
    networks:
      - net
    volumes:
      - postgres:/var/lib/postgres

  webapp:
    container_name: webapp
    build:
      context: .
      dockerfile: docker/webapp.Dockerfile
    environment:
      - FLASK_ENV=docker
      - DB_URI=postgresql://postgres@postgres:5432/ngk
    ports:
      - 5000:5000
    networks:
      - net
    links:
      - postgres

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - 5001:5001
    links:
      - webapp
    networks:
      - net
    volumes:
    - ./docker/nginx.conf:/etc/nginx/nginx.conf

  scan_comments:
    container_name: scan_comments
    build:
      context: .
      dockerfile: docker/scan_comments.Dockerfile
    environment:
      - DB_URI=postgresql://postgres@postgres:5432/ngk
      - LOG_FILE=/var/log/scan_comments.log
    networks:
      - net
    links:
      - postgres

  fetch_posts:
    container_name: fetch_posts
    build:
      context: .
      dockerfile: docker/fetch_posts.Dockerfile
    environment:
      - DB_URI=postgresql://postgres@postgres:5432/ngk
      - LOG_FILE=/var/log/fetch_posts.log
    networks:
      - net
    links:
      - postgres

volumes:
  postgres:

networks:
  net:
